# Generated by Django 3.2.2 on 2021-05-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heifer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
    ]
